-- =========================================================
--  MICROFINANCE - Script Oracle initial
--  Serveur BD : 192.168.1.20:1521
-- =========================================================

-- 1. SEQUENCES
CREATE SEQUENCE CLIENT_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GESTIONNAIRE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPTE_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRANSACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RAPPORT_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 2. TABLE CLIENTS
CREATE TABLE CLIENTS (
    ID_CLIENT       NUMBER PRIMARY KEY,
    NOM             VARCHAR2(100) NOT NULL,
    PRENOM          VARCHAR2(100) NOT NULL,
    TELEPHONE       VARCHAR2(20)  NOT NULL UNIQUE,
    EMAIL           VARCHAR2(150) UNIQUE,
    ADRESSE         VARCHAR2(255) NOT NULL,
    NUMERO_CNI      VARCHAR2(50)  UNIQUE,
    DATE_NAISSANCE  DATE,
    DATE_INSCRIPTION DATE NOT NULL,
    MOT_DE_PASSE    VARCHAR2(255) NOT NULL,
    ROLE            VARCHAR2(30)  DEFAULT 'ROLE_CLIENT' NOT NULL,
    ACTIF           NUMBER(1)     DEFAULT 1 NOT NULL
);

-- 3. TABLE GESTIONNAIRES
CREATE TABLE GESTIONNAIRES (
    ID_GESTIONNAIRE NUMBER PRIMARY KEY,
    NOM             VARCHAR2(100) NOT NULL,
    PRENOM          VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(150) NOT NULL UNIQUE,
    MOT_DE_PASSE    VARCHAR2(255) NOT NULL,
    ROLE            VARCHAR2(30)  NOT NULL,
    DATE_EMBAUCHE   DATE,
    ACTIF           NUMBER(1)     DEFAULT 1 NOT NULL
);

-- 4. TABLE COMPTES
CREATE TABLE COMPTES (
    ID_COMPTE           NUMBER PRIMARY KEY,
    NUMERO_COMPTE       VARCHAR2(20)    NOT NULL UNIQUE,
    SOLDE               NUMBER(15,2)    DEFAULT 0 NOT NULL,
    STATUT              VARCHAR2(20)    DEFAULT 'EN_ATTENTE' NOT NULL,
    DATE_OUVERTURE      TIMESTAMP       NOT NULL,
    DATE_FERMETURE      TIMESTAMP,
    PLAFOND_RETRAIT     NUMBER(15,2)    DEFAULT 500000,
    MONTANT_MIN_SOLDE   NUMBER(15,2)    DEFAULT 5000,
    TAUX_AGIOS          NUMBER(5,4)     DEFAULT 0.0050,
    ID_CLIENT           NUMBER          NOT NULL,
    CONSTRAINT FK_COMPTE_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT)
);

-- 5. TABLE TRANSACTIONS (SINGLE TABLE INHERITANCE)
CREATE TABLE TRANSACTIONS (
    ID_TRANSACTION      NUMBER PRIMARY KEY,
    TYPE_TRANSACTION    VARCHAR2(20)    NOT NULL,  -- VERSEMENT / RETRAIT / VIREMENT
    MONTANT             NUMBER(15,2)    NOT NULL,
    DATE_HEURE          TIMESTAMP       NOT NULL,
    STATUT              VARCHAR2(20)    DEFAULT 'EN_COURS' NOT NULL,
    REFERENCE           VARCHAR2(30)    UNIQUE,
    DESCRIPTION         VARCHAR2(255),
    ID_COMPTE           NUMBER          NOT NULL,
    -- Versement
    SOURCE_VERSEMENT    VARCHAR2(100),
    -- Retrait
    CANAL_RETRAIT       VARCHAR2(50),
    -- Virement
    ID_COMPTE_DEST      NUMBER,
    CONSTRAINT FK_TX_COMPTE  FOREIGN KEY (ID_COMPTE)      REFERENCES COMPTES(ID_COMPTE),
    CONSTRAINT FK_TX_DEST    FOREIGN KEY (ID_COMPTE_DEST) REFERENCES COMPTES(ID_COMPTE)
);

-- 6. TABLE RAPPORTS
CREATE TABLE RAPPORTS (
    ID_RAPPORT          NUMBER PRIMARY KEY,
    TYPE_RAPPORT        VARCHAR2(50)    NOT NULL,
    PERIODE_DEBUT       DATE            NOT NULL,
    PERIODE_FIN         DATE            NOT NULL,
    DATE_GENERATION     TIMESTAMP       NOT NULL,
    CONTENU             CLOB,
    ID_GESTIONNAIRE     NUMBER,
    CONSTRAINT FK_RAPPORT_GEST FOREIGN KEY (ID_GESTIONNAIRE) REFERENCES GESTIONNAIRES(ID_GESTIONNAIRE)
);

-- 7. INDEXES
CREATE INDEX IDX_COMPTES_CLIENT    ON COMPTES(ID_CLIENT);
CREATE INDEX IDX_TX_COMPTE         ON TRANSACTIONS(ID_COMPTE);
CREATE INDEX IDX_TX_DATE           ON TRANSACTIONS(DATE_HEURE);
CREATE INDEX IDX_TX_STATUT         ON TRANSACTIONS(STATUT);

-- 8. DONNÉES INITIALES : Compte admin et gestionnaire par défaut
-- (mot de passe : Admin@2024  hashé BCrypt)
INSERT INTO GESTIONNAIRES VALUES (
    GESTIONNAIRE_SEQ.NEXTVAL, 'Admin', 'Système',
    'admin@microfinance.local',
    '$2a$12$N5FbFJpT3rV7LjqWsW6lPOdHDq9gvR2zBzuK8m5Y1j0WcAtXnrVkm',
    'ROLE_ADMIN_SYSTEME', SYSDATE, 1
);

INSERT INTO GESTIONNAIRES VALUES (
    GESTIONNAIRE_SEQ.NEXTVAL, 'Diallo', 'Aminata',
    'gestionnaire@microfinance.local',
    '$2a$12$N5FbFJpT3rV7LjqWsW6lPOdHDq9gvR2zBzuK8m5Y1j0WcAtXnrVkm',
    'ROLE_GESTIONNAIRE', SYSDATE, 1
);

COMMIT;
